[build]
  functions = "netlify/functions"
  publish = ".next"
  command = "npm run build"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["fs", "path"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs" 